### ISSUE TITLE
Getting a `invalid character '/' after top-level value` error

### ISSUE THREAD

**Issue by vlad-stoian** [cloudfoundry/bosh-deployment-resource#35] opened 2018-01-10 11:47 UTC
Hi,

We've recently upgraded to use the latest `bosh-deployment-resource` to get the jumpbox goodies and we started getting this message randomly, and the **put** step crashing:
```
invalid character '/' after top-level value
```

This happens only some of the times, even if the configuration doesn't change at all. The message appears right after the deployment finishes.

Do you know what might be causing it?

Thank you,
Vlad and Alberto ( @albertoleal )

**Comment by sesmith177** [comment] 2018-01-10 20:09
we (garden-windows team) are seeing this issue as well

**Comment by drich10** [comment] 2018-01-11 15:43
I haven't witnessed the issue myself. Could you paste you resource/task configurations here with secrets scrubbed? Along with the logs if possible. I'd love to address it but I'm not quite sure where to start without config/logs from cases of this occurring.

**Comment by sesmith177** [comment] 2018-01-11 16:00
@drich10 We suspect (but haven't proven yet) that the error happens when more than one release gets updated, e.g.:

```
Task 122 done
  releases:
  - name: uaa
-   sha1: b49b0caaf46d8f94d67979f9e46d9c22907bd451
+   sha1: ce435cbb190611db2685f135edc49f9eab6bab89
-   url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=53.1
+   url: https://bosh.io/d/github.com/cloudfoundry/uaa-release?v=53.3
-   version: '53.1'
+   version: '53.3'
  - name: garden-windows
-   version: 0.13.0+dev.1515616745
+   version: 0.13.0+dev.1515681663
  - name: winc
-   version: 0.7.0+dev.1515616745
+   version: 0.7.0+dev.1515681661
  - name: windows2016fs
-   version: 0.0.6+dev.1515616746
+   version: 0.0.6+dev.1515681661
  - name: bosh-dns
-   version: 0.2.0+dev.1515616747
+   version: 0.2.0+dev.1515681661

Task 123

Task 123 | 14:45:51 | Preparing deployment: Preparing deployment (00:00:04)
Task 123 | 14:46:00 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 123 | 14:46:01 | Compiling packages: uaa/1c756d8b2bbf320117822f2eb557c0f8a3701d00 (00:02:17)
Task 123 | 14:48:41 | Updating instance uaa: uaa/f6ecd22f-9796-4786-be4c-fdf13518bc86 (0) (canary) (00:01:59)

Task 123 Started  Thu Jan 11 14:45:51 UTC 2018
Task 123 Finished Thu Jan 11 14:50:40 UTC 2018
Task 123 Duration 00:04:49
Task 123 done
Using environment 'https://10.85.51.6:25555' as client 'admin'

Task 124

Task 124 | 14:50:43 | Deleting dns blobs: DNS blobs (00:00:00)

Task 124 Started  Thu Jan 11 14:50:43 UTC 2018
Task 124 Finished Thu Jan 11 14:50:43 UTC 2018
Task 124 Duration 00:00:00
Task 124 done

invalid character '/' after top-level value
```

When only one release is updated, we don't see the error:
```
  releases:
  - name: winc
-   version: 0.7.0+dev.1515684087
+   version: 0.7.0+dev.1515686043
Task 81

Task 81 | 15:54:48 | Preparing deployment: Preparing deployment (00:00:04)
Task 81 | 15:54:56 | Preparing package compilation: Finding packages to compile (00:00:01)

Task 81 Started  Thu Jan 11 15:54:48 UTC 2018
Task 81 Finished Thu Jan 11 15:54:57 UTC 2018
Task 81 Duration 00:00:09
Task 81 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

Task 82

Task 82 | 15:54:59 | Deleting releases: winc/0.7.0+dev.1515617626 (00:00:00)
Task 82 | 15:54:59 | Deleting dns blobs: DNS blobs (00:00:00)

Task 82 Started  Thu Jan 11 15:54:59 UTC 2018
Task 82 Finished Thu Jan 11 15:54:59 UTC 2018
Task 82 Duration 00:00:00
Task 82 done
```

**Comment by aminjam** [comment] 2018-01-11 16:20
@drich10 It's worth noting that this started to occur when we upgraded to bbl 5.x. We were previously using this resource with a public bosh director and didn't see this error.

**Comment by vlad-stoian** [comment] 2018-01-11 16:29
This is our output. We only have one release that gets updated. We're also using the jumpbox feature if it matters.

```
Using environment 'https://10.0.0.6:25555' as client 'admin'

 100.00% 20.24 MB/s 1s
Task 756

Task 756 | 16:20:59 | Extracting release: Extracting release (00:00:00)
Task 756 | 16:20:59 | Verifying manifest: Verifying manifest (00:00:00)
Task 756 | 16:20:59 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 756 | 16:20:59 | Creating new packages: cf-rabbitmq-smoke-tests/fd0e4b850b820d1ff7ea245b28f89d9c0ac5785d002498e76550ac9e86f6e850 (00:00:01)
Task 756 | 16:21:00 | Processing 3 existing packages: Processing 3 existing packages (00:00:00)
Task 756 | 16:21:00 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Task 756 | 16:21:00 | Release has been created: rabbitmq-on-demand-adapter/18.0.0-dev.1 (00:00:00)

Task 756 Started  Thu Jan 11 16:20:59 UTC 2018
Task 756 Finished Thu Jan 11 16:21:00 UTC 2018
Task 756 Duration 00:00:01
Task 756 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

 100.00% 152.51 KB/s 0s
Task 757

Task 757 | 16:21:02 | Extracting release: Extracting release (00:00:00)
Task 757 | 16:21:02 | Verifying manifest: Verifying manifest (00:00:00)
Task 757 | 16:21:02 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 757 | 16:21:02 | Processing 12 existing packages: Processing 12 existing packages (00:00:00)
Task 757 | 16:21:02 | Processing 8 existing jobs: Processing 8 existing jobs (00:00:00)
Task 757 | 16:21:02 | Release has been created: on-demand-service-broker/0.19.0 (00:00:00)

Task 757 Started  Thu Jan 11 16:21:02 UTC 2018
Task 757 Finished Thu Jan 11 16:21:02 UTC 2018
Task 757 Duration 00:00:00
Task 757 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

 100.00% 124.87 KB/s 0s
Task 758

Task 758 | 16:21:05 | Extracting release: Extracting release (00:00:00)
Task 758 | 16:21:05 | Verifying manifest: Verifying manifest (00:00:00)
Task 758 | 16:21:05 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 758 | 16:21:06 | Processing 7 existing packages: Processing 7 existing packages (00:00:00)
Task 758 | 16:21:06 | Processing 3 existing jobs: Processing 3 existing jobs (00:00:00)
Task 758 | 16:21:06 | Release has been created: cf-rabbitmq/235.0.0 (00:00:00)

Task 758 Started  Thu Jan 11 16:21:05 UTC 2018
Task 758 Finished Thu Jan 11 16:21:06 UTC 2018
Task 758 Duration 00:00:01
Task 758 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

 100.00% 157.58 KB/s 0s
Task 759

Task 759 | 16:21:08 | Extracting release: Extracting release (00:00:00)
Task 759 | 16:21:08 | Verifying manifest: Verifying manifest (00:00:00)
Task 759 | 16:21:08 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 759 | 16:21:08 | Processing 10 existing packages: Processing 10 existing packages (00:00:00)
Task 759 | 16:21:08 | Processing 7 existing jobs: Processing 7 existing jobs (00:00:00)
Task 759 | 16:21:08 | Release has been created: routing/0.169.0 (00:00:00)

Task 759 Started  Thu Jan 11 16:21:08 UTC 2018
Task 759 Finished Thu Jan 11 16:21:08 UTC 2018
Task 759 Duration 00:00:00
Task 759 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

 100.00% 81.12 KB/s 0s
Task 760

Task 760 | 16:21:11 | Extracting release: Extracting release (00:00:00)
Task 760 | 16:21:11 | Verifying manifest: Verifying manifest (00:00:00)
Task 760 | 16:21:11 | Resolving package dependencies: Resolving package dependencies (00:00:00)
Task 760 | 16:21:11 | Processing 2 existing packages: Processing 2 existing packages (00:00:00)
Task 760 | 16:21:11 | Processing 2 existing jobs: Processing 2 existing jobs (00:00:00)
Task 760 | 16:21:11 | Release has been created: syslog-migration/10 (00:00:00)

Task 760 Started  Thu Jan 11 16:21:11 UTC 2018
Task 760 Finished Thu Jan 11 16:21:11 UTC 2018
Task 760 Duration 00:00:00
Task 760 done
Using environment 'https://10.0.0.6:25555' as client 'admin'

Stemcell 'bosh-google-kvm-ubuntu-trusty-go_agent/3363.46' already exists.
Using environment 'https://10.0.0.6:25555' as client 'admin'

Using deployment 'rabbitmq-on-demand-broker-ci'

  releases:
  - name: rabbitmq-on-demand-adapter
-   version: 17.0.0-dev.43
+   version: 18.0.0-dev.1
Task 761

Task 761 | 16:21:13 | Preparing deployment: Preparing deployment (00:00:00)
Task 761 | 16:21:13 | Preparing package compilation: Finding packages to compile (00:00:01)
Task 761 | 16:21:14 | Compiling packages: cf-rabbitmq-smoke-tests/fd0e4b850b820d1ff7ea245b28f89d9c0ac5785d002498e76550ac9e86f6e850 (00:00:54)

Task 761 Started  Thu Jan 11 16:21:13 UTC 2018
Task 761 Finished Thu Jan 11 16:22:08 UTC 2018
Task 761 Duration 00:00:55
Task 761 done

invalid character '/' after top-level value
```

**Comment by vlad-stoian** [comment] 2018-01-11 16:32
As for configuration, here it is.

Resource config:
```
- name: bosh-for-rabbitmq-on-demand-adapter
  type: cloudfoundry-bosh-deployment
  source: {}
```
Task:
```
  - put: bosh-for-rabbitmq-on-demand-adapter
    params:
      manifest: manifest/manifest.yml
      releases:
      - release/*.tgz
      - pivnet-for-on-demand-service-broker/*.tgz
      - s3-for-cf-rabbitmq/*.tgz
      - bosh-io-release-for-routing/*.tgz
      - github-release-for-syslog-migration/*.tgz
      source_file: source_file/source_file.yml
      stemcells:
      - pivnet-stemcell/*.tgz
    on_failure:
      put: rabbitmq-on-demand-adapter-lock
      params:
        release: rabbitmq-on-demand-adapter-lock
    ensure:
      put: release-version
      resource: rabbitmq-on-demand-adapter-version
      params:
        file: release-version/number
    attempts: 1
```


Also source file:
```
---
client: redacted
client_secret: redacted
ca_cert: |
  -----BEGIN CERTIFICATE-----
  redacted
  -----END CERTIFICATE-----
deployment: rabbitmq-on-demand-broker-ci
target: https://10.0.0.6:25555
jumpbox_url: 35.189.250.37:22
jumpbox_ssh_key: |
  -----BEGIN RSA PRIVATE KEY-----
  redacted
  -----END RSA PRIVATE KEY-----
```

**Comment by sesmith177** [comment] 2018-01-11 19:18
@drich10 it looks like the problem is the socks5 proxy is writing to stdout, resulting in invalid json:

```
2018/01/11 19:12:06 [ERR] socks: Failed to handle request: read tcp 127.0.0.1:38846->127.0.0.1:34038: read: connection reset by peer
2018/01/11 19:14:45 [ERR] socks: Failed to handle request: read tcp 127.0.0.1:38846->127.0.0.1:34216: read: connection reset by peer
2018/01/11 19:15:28 [ERR] socks: Failed to handle request: read tcp 127.0.0.1:38846->127.0.0.1:34262: read: connection reset by peer
2018/01/11 19:15:29 [ERR] socks: Failed to handle request: read tcp 127.0.0.1:38846->127.0.0.1:34284: read: connection reset by peer
{
  "version": {
    "manifest_sha1": "171020e2eee8bf310ebebc75c18f0abeffeacb8f",
    "target": "https://10.85.51.6:25555"
  },
  "metadata": [
    {
      "name": "release",
      "value": "winc v0.7.0+dev.1515697686"
    },
    {
      "name": "release",
      "value": "windows2016fs v0.0.6+dev.1515697687"
    },
    {
      "name": "release",
      "value": "garden-windows v0.13.0+dev.1515697687"
    },
    {
      "name": "release",
      "value": "bosh-dns v0.2.0+dev.1515697687"
    },
    {
      "name": "stemcell",
      "value": "bosh-vsphere-esxi-ubuntu-trusty-go_agent v3468.16"
    },
    {
      "name": "stemcell",
      "value": "bosh-vsphere-esxi-windows2012R2-go_agent v1200.12"
    },
    {
      "name": "stemcell",
      "value": "bosh-vsphere-esxi-windows2016-go_agent v1709.1"
    }
  ]
}
```

**Comment by sesmith177** [comment] 2018-01-11 20:41
@drich10 @vlad-stoian  we discarded the socks5 log output as a workaround:

https://github.com/greenhouse-org/bosh-deployment-resource/commit/c4fc7e3cadeef4898c7daa1978295efc450fbabb

there is a container image at pivotalgreenhouse/bosh-deployment-resource that we are using

**Comment by drich10** [comment] 2018-01-16 16:03
Thanks for digging into this! I have pushed the same bandaid @sesmith177 did above as a workaround. I'll be opening an issue on the https://github.com/cloudfoundry/socks5-proxy repo to discuss a more permanent option. I'll close this issue once the build is published and I've submitted the other issue.

**Comment by drich10** [comment] 2018-01-16 16:28
Published https://github.com/cloudfoundry/bosh-deployment-resource/tree/v2.8.2 with the workaround. Thanks for all the help. Please re-open if you continue to see issues.

**Closed as completed by drich10** 2018-01-16 16:28 UTC
